package events

// Code generated by generate_events.go; DO NOT EDIT.

import "github.com/gagliardetto/solana-go"
import "math/big"

// EntryFeeUpdatedEvent event struct
type EntryFeeUpdatedEvent struct {
	AccountantKey solana.PublicKey
	EntryFee      big.Int
}

// PerformanceFeeUpdatedEvent event struct
type PerformanceFeeUpdatedEvent struct {
	AccountantKey  solana.PublicKey
	PerformanceFee big.Int
}

// RedemptionFeeUpdatedEvent event struct
type RedemptionFeeUpdatedEvent struct {
	AccountantKey solana.PublicKey
	RedemptionFee big.Int
}
