package events

// Code generated by generate_events.go; DO NOT EDIT.

import (
	"github.com/Tsisar/solana-indexer/subgraph/types"
	"github.com/gagliardetto/solana-go"
)

// EntryFeeUpdatedEvent event struct
type EntryFeeUpdatedEvent struct {
	AccountantKey solana.PublicKey
	EntryFee      types.BigInt
}

// PerformanceFeeUpdatedEvent event struct
type PerformanceFeeUpdatedEvent struct {
	AccountantKey  solana.PublicKey
	PerformanceFee types.BigInt
}

// RedemptionFeeUpdatedEvent event struct
type RedemptionFeeUpdatedEvent struct {
	AccountantKey solana.PublicKey
	RedemptionFee types.BigInt
}
