package events

// Code generated by generate_events.go; DO NOT EDIT.

import "github.com/gagliardetto/solana-go"
import "math/big"

// DepositLimitSetEvent event struct
type DepositLimitSetEvent struct {
	AccountKey   solana.PublicKey
	DepositLimit big.Int
	Timestamp    big.Int
}

// EmergencyWithdrawEvent event struct
type EmergencyWithdrawEvent struct {
	StrategyKey      solana.PublicKey
	VaultKey         solana.PublicKey
	AssetMint        solana.PublicKey
	Recipient        solana.PublicKey
	RedeemableAmount big.Int
	ScaledRatio      big.Int
	Timestamp        big.Int
}

// FundManagerDeployFundsEvent event struct
type FundManagerDeployFundsEvent struct {
	AccountKey     solana.PublicKey
	Vault          solana.PublicKey
	Amount         big.Int
	DeployedAmount big.Int
	TotalInvested  big.Int
	TotalDeployed  big.Int
	Timestamp      big.Int
}

// FundManagerEmergencyWithdrawEvent event struct
type FundManagerEmergencyWithdrawEvent struct {
	AccountKey        solana.PublicKey
	Vault             solana.PublicKey
	Amount            big.Int
	AmountTransferred big.Int
	TotalInvested     big.Int
	Timestamp         big.Int
}

// FundManagerFreeFundsEvent event struct
type FundManagerFreeFundsEvent struct {
	AccountKey        solana.PublicKey
	Vault             solana.PublicKey
	Amount            big.Int
	AmountTransferred big.Int
	TotalInvested     big.Int
	TotalFreed        big.Int
	Timestamp         big.Int
}

// FundManagerHarvestAndReportEvent event struct
type FundManagerHarvestAndReportEvent struct {
	AccountKey    solana.PublicKey
	Vault         solana.PublicKey
	TotalInvested big.Int
	TotalAssets   big.Int
	Timestamp     big.Int
}

// FundManagerStrategyStateUpdateEvent event struct
type FundManagerStrategyStateUpdateEvent struct {
	AccountKey    solana.PublicKey
	Vault         solana.PublicKey
	TotalAssets   big.Int
	TotalInvested big.Int
	TotalIdle     big.Int
	TotalDeployed big.Int
	TotalFreed    big.Int
	Timestamp     big.Int
}

// HarvestAndReportDTFEvent event struct
type HarvestAndReportDTFEvent struct {
	AccountKey  solana.PublicKey
	TotalAssets big.Int
	Timestamp   big.Int
}

// MinDeployAmountSetEvent event struct
type MinDeployAmountSetEvent struct {
	AccountKey      solana.PublicKey
	MinDeployAmount big.Int
	Timestamp       big.Int
}

// OrcaAfterSwapEvent event struct
type OrcaAfterSwapEvent struct {
	AccountKey              solana.PublicKey
	Vault                   solana.PublicKey
	Buy                     bool
	Amount                  big.Int
	TotalInvested           big.Int
	WhirlpoolId             solana.PublicKey
	UnderlyingMint          solana.PublicKey
	UnderlyingDecimals      big.Int
	AssetMint               solana.PublicKey
	AssetAmount             big.Int
	AssetDecimals           big.Int
	TotalAssets             big.Int
	IdleUnderlying          big.Int
	AToBForPurchase         bool
	UnderlyingBalanceBefore big.Int
	UnderlyingBalanceAfter  big.Int
	AssetBalanceBefore      big.Int
	AssetBalanceAfter       big.Int
	Timestamp               big.Int
}

// OrcaInitEvent event struct
type OrcaInitEvent struct {
	AccountKey      solana.PublicKey
	WhirlpoolId     solana.PublicKey
	AssetMint       solana.PublicKey
	AssetDecimals   big.Int
	AToBForPurchase bool
}

// SetPerformanceFeeEvent event struct
type SetPerformanceFeeEvent struct {
	AccountKey solana.PublicKey
	Fee        big.Int
}

// StrategyDeployFundsEvent event struct
type StrategyDeployFundsEvent struct {
	AccountKey solana.PublicKey
	Amount     big.Int
	Timestamp  big.Int
}

// StrategyDepositEvent event struct
type StrategyDepositEvent struct {
	AccountKey  solana.PublicKey
	Amount      big.Int
	TotalAssets big.Int
}

// StrategyFreeFundsEvent event struct
type StrategyFreeFundsEvent struct {
	AccountKey solana.PublicKey
	Amount     big.Int
	Timestamp  big.Int
}

// StrategyInitEvent event struct
type StrategyInitEvent struct {
	AccountKey         solana.PublicKey
	StrategyType       string
	Vault              solana.PublicKey
	UnderlyingMint     solana.PublicKey
	UnderlyingTokenAcc solana.PublicKey
	UnderlyingDecimals big.Int
	DepositLimit       big.Int
	DepositPeriodEnds  big.Int
	LockPeriodEnds     big.Int
}

// StrategyReallocEvent event struct
type StrategyReallocEvent struct {
	Strategy  solana.PublicKey
	NewSize   big.Int
	Timestamp big.Int
}

// StrategyShutdownEvent event struct
type StrategyShutdownEvent struct {
	AccountKey solana.PublicKey
	Shutdown   bool
	Timestamp  big.Int
}

// StrategyWithdrawEvent event struct
type StrategyWithdrawEvent struct {
	AccountKey  solana.PublicKey
	Amount      big.Int
	TotalAssets big.Int
}

// TotalInvestedUpdatedEvent event struct
type TotalInvestedUpdatedEvent struct {
	AccountKey            solana.PublicKey
	Vault                 solana.PublicKey
	PreviousTotalInvested big.Int
	TotalInvested         big.Int
	Timestamp             big.Int
}
