package events

// Code generated by generate_events.go; DO NOT EDIT.

import "github.com/gagliardetto/solana-go"
import "math/big"

// StrategyReportedEvent event struct
type StrategyReportedEvent struct {
	VaultKey     solana.PublicKey
	StrategyKey  solana.PublicKey
	Gain         big.Int
	Loss         big.Int
	CurrentDebt  big.Int
	ProtocolFees big.Int
	TotalFees    big.Int
	TotalShares  big.Int
	SharePrice   big.Int
	Timestamp    big.Int
}

// UpdatedCurrentDebtForStrategyEvent event struct
type UpdatedCurrentDebtForStrategyEvent struct {
	VaultKey    solana.PublicKey
	StrategyKey solana.PublicKey
	TotalIdle   big.Int
	TotalDebt   big.Int
	NewDebt     big.Int
}

// VaultAddStrategyEvent event struct
type VaultAddStrategyEvent struct {
	VaultKey    solana.PublicKey
	StrategyKey solana.PublicKey
	CurrentDebt big.Int
	MaxDebt     big.Int
	LastUpdate  big.Int
	IsActive    bool
}

// VaultDepositEvent event struct
type VaultDepositEvent struct {
	VaultKey     solana.PublicKey
	TotalDebt    big.Int
	TotalIdle    big.Int
	TotalShare   big.Int
	Amount       big.Int
	Share        big.Int
	TokenAccount solana.PublicKey
	ShareAccount solana.PublicKey
	TokenMint    solana.PublicKey
	ShareMint    solana.PublicKey
	Authority    solana.PublicKey
	SharePrice   big.Int
	Timestamp    big.Int
}

// VaultEmergencyWithdrawEvent event struct
type VaultEmergencyWithdrawEvent struct {
	VaultKey            solana.PublicKey
	Recipient           solana.PublicKey
	Shares              big.Int
	VaultTotalShares    big.Int
	ScaledRatio         big.Int
	StrategiesProcessed big.Int
	Timestamp           big.Int
}

// VaultInitEvent event struct
type VaultInitEvent struct {
	VaultKey              solana.PublicKey
	UnderlyingToken       TokenData
	Accountant            solana.PublicKey
	ShareToken            TokenData
	DepositLimit          big.Int
	UserDepositLimit      big.Int
	MinUserDeposit        big.Int
	KycVerifiedOnly       bool
	DirectDepositEnabled  bool
	DirectWithdrawEnabled bool
	MinimumTotalIdle      big.Int
	WhitelistedOnly       bool
	ProfitMaxUnlockTime   big.Int
}

// VaultRemoveStrategyEvent event struct
type VaultRemoveStrategyEvent struct {
	VaultKey    solana.PublicKey
	StrategyKey solana.PublicKey
	RemovedAt   big.Int
}

// VaultShutDownEvent event struct
type VaultShutDownEvent struct {
	VaultKey solana.PublicKey
	Shutdown bool
}

// VaultUpdateAccountantEvent event struct
type VaultUpdateAccountantEvent struct {
	VaultKey      solana.PublicKey
	NewAccountant solana.PublicKey
	Timestamp     big.Int
}

// VaultUpdateDepositLimitEvent event struct
type VaultUpdateDepositLimitEvent struct {
	VaultKey  solana.PublicKey
	NewLimit  big.Int
	Timestamp big.Int
}

// VaultUpdateDirectWithdrawEnabledEvent event struct
type VaultUpdateDirectWithdrawEnabledEvent struct {
	VaultKey                 solana.PublicKey
	NewDirectWithdrawEnabled bool
	Timestamp                big.Int
}

// VaultUpdateMinTotalIdleEvent event struct
type VaultUpdateMinTotalIdleEvent struct {
	VaultKey        solana.PublicKey
	NewMinTotalIdle big.Int
	Timestamp       big.Int
}

// VaultUpdateMinUserDepositEvent event struct
type VaultUpdateMinUserDepositEvent struct {
	VaultKey          solana.PublicKey
	NewMinUserDeposit big.Int
	Timestamp         big.Int
}

// VaultUpdateProfitMaxUnlockTimeEvent event struct
type VaultUpdateProfitMaxUnlockTimeEvent struct {
	VaultKey               solana.PublicKey
	NewProfitMaxUnlockTime big.Int
	Timestamp              big.Int
}

// VaultUpdateUserDepositLimitEvent event struct
type VaultUpdateUserDepositLimitEvent struct {
	VaultKey            solana.PublicKey
	NewUserDepositLimit big.Int
	Timestamp           big.Int
}

// VaultUpdateWhitelistedOnlyEvent event struct
type VaultUpdateWhitelistedOnlyEvent struct {
	VaultKey           solana.PublicKey
	NewWhitelistedOnly bool
	Timestamp          big.Int
}

// VaultWithdrawlEvent event struct
type VaultWithdrawlEvent struct {
	VaultKey         solana.PublicKey
	TotalIdle        big.Int
	TotalShare       big.Int
	AssetsToTransfer big.Int
	SharesToBurn     big.Int
	TokenAccount     solana.PublicKey
	ShareAccount     solana.PublicKey
	TokenMint        solana.PublicKey
	ShareMint        solana.PublicKey
	Authority        solana.PublicKey
	SharePrice       big.Int
	Timestamp        big.Int
}

// WhitelistUpdatedEvent event struct
type WhitelistUpdatedEvent struct {
	User        solana.PublicKey
	Whitelisted bool
}

// WithdrawalRequestCanceledEvent event struct
type WithdrawalRequestCanceledEvent struct {
	User      solana.PublicKey
	Vault     solana.PublicKey
	Index     big.Int
	Timestamp big.Int
}

// WithdrawalRequestFulfilledEvent event struct
type WithdrawalRequestFulfilledEvent struct {
	User      solana.PublicKey
	Vault     solana.PublicKey
	Amount    big.Int
	Index     big.Int
	Timestamp big.Int
}

// WithdrawalRequestedEvent event struct
type WithdrawalRequestedEvent struct {
	User        solana.PublicKey
	Vault       solana.PublicKey
	Recipient   solana.PublicKey
	Shares      big.Int
	Amount      big.Int
	MaxLoss     big.Int
	FeeShares   big.Int
	Index       big.Int
	Timestamp   big.Int
	PriorityFee big.Int
}
