package events

// Code generated by generate_events.go; DO NOT EDIT.

import (
	"github.com/Tsisar/solana-indexer/internal/subgraph/types"
	"github.com/gagliardetto/solana-go"
)

// DepositLimitSetEvent event struct
type DepositLimitSetEvent struct {
	AccountKey   solana.PublicKey
	DepositLimit types.BigInt
	Timestamp    types.BigInt
}

// EmergencyWithdrawEvent event struct
type EmergencyWithdrawEvent struct {
	StrategyKey      solana.PublicKey
	VaultKey         solana.PublicKey
	AssetMint        solana.PublicKey
	Recipient        solana.PublicKey
	RedeemableAmount types.BigInt
	ScaledRatio      types.BigInt
	Timestamp        types.BigInt
}

// FundManagerDeployFundsEvent event struct
type FundManagerDeployFundsEvent struct {
	AccountKey     solana.PublicKey
	Vault          solana.PublicKey
	Amount         types.BigInt
	DeployedAmount types.BigInt
	TotalInvested  types.BigInt
	TotalDeployed  types.BigInt
	Timestamp      types.BigInt
}

// FundManagerEmergencyWithdrawEvent event struct
type FundManagerEmergencyWithdrawEvent struct {
	AccountKey        solana.PublicKey
	Vault             solana.PublicKey
	Amount            types.BigInt
	AmountTransferred types.BigInt
	TotalInvested     types.BigInt
	Timestamp         types.BigInt
}

// FundManagerFreeFundsEvent event struct
type FundManagerFreeFundsEvent struct {
	AccountKey        solana.PublicKey
	Vault             solana.PublicKey
	Amount            types.BigInt
	AmountTransferred types.BigInt
	TotalInvested     types.BigInt
	TotalFreed        types.BigInt
	Timestamp         types.BigInt
}

// FundManagerHarvestAndReportEvent event struct
type FundManagerHarvestAndReportEvent struct {
	AccountKey    solana.PublicKey
	Vault         solana.PublicKey
	TotalInvested types.BigInt
	TotalAssets   types.BigInt
	Timestamp     types.BigInt
}

// FundManagerStrategyStateUpdateEvent event struct
type FundManagerStrategyStateUpdateEvent struct {
	AccountKey    solana.PublicKey
	Vault         solana.PublicKey
	TotalAssets   types.BigInt
	TotalInvested types.BigInt
	TotalIdle     types.BigInt
	TotalDeployed types.BigInt
	TotalFreed    types.BigInt
	Timestamp     types.BigInt
}

// HarvestAndReportDTFEvent event struct
type HarvestAndReportDTFEvent struct {
	AccountKey  solana.PublicKey
	TotalAssets types.BigInt
	Timestamp   types.BigInt
}

// MinDeployAmountSetEvent event struct
type MinDeployAmountSetEvent struct {
	AccountKey      solana.PublicKey
	MinDeployAmount types.BigInt
	Timestamp       types.BigInt
}

// OrcaAfterSwapEvent event struct
type OrcaAfterSwapEvent struct {
	AccountKey              solana.PublicKey
	Vault                   solana.PublicKey
	Buy                     bool
	Amount                  types.BigInt
	TotalInvested           types.BigInt
	WhirlpoolId             solana.PublicKey
	UnderlyingMint          solana.PublicKey
	UnderlyingDecimals      types.BigInt
	AssetMint               solana.PublicKey
	AssetAmount             types.BigInt
	AssetDecimals           types.BigInt
	TotalAssets             types.BigInt
	IdleUnderlying          types.BigInt
	AToBForPurchase         bool
	UnderlyingBalanceBefore types.BigInt
	UnderlyingBalanceAfter  types.BigInt
	AssetBalanceBefore      types.BigInt
	AssetBalanceAfter       types.BigInt
	Timestamp               types.BigInt
}

// OrcaInitEvent event struct
type OrcaInitEvent struct {
	AccountKey      solana.PublicKey
	WhirlpoolId     solana.PublicKey
	AssetMint       solana.PublicKey
	AssetDecimals   types.BigInt
	AToBForPurchase bool
}

// SetPerformanceFeeEvent event struct
type SetPerformanceFeeEvent struct {
	AccountKey solana.PublicKey
	Fee        types.BigInt
}

// StrategyDeployFundsEvent event struct
type StrategyDeployFundsEvent struct {
	AccountKey solana.PublicKey
	Amount     types.BigInt
	Timestamp  types.BigInt
}

// StrategyDepositEvent event struct
type StrategyDepositEvent struct {
	AccountKey  solana.PublicKey
	Amount      types.BigInt
	TotalAssets types.BigInt
}

// StrategyFreeFundsEvent event struct
type StrategyFreeFundsEvent struct {
	AccountKey solana.PublicKey
	Amount     types.BigInt
	Timestamp  types.BigInt
}

// StrategyInitEvent event struct
type StrategyInitEvent struct {
	AccountKey         solana.PublicKey
	StrategyType       string
	Vault              solana.PublicKey
	UnderlyingMint     solana.PublicKey
	UnderlyingTokenAcc solana.PublicKey
	UnderlyingDecimals types.BigInt
	DepositLimit       types.BigInt
	DepositPeriodEnds  types.BigInt
	LockPeriodEnds     types.BigInt
}

// StrategyReallocEvent event struct
type StrategyReallocEvent struct {
	Strategy  solana.PublicKey
	NewSize   types.BigInt
	Timestamp types.BigInt
}

// StrategyShutdownEvent event struct
type StrategyShutdownEvent struct {
	AccountKey solana.PublicKey
	Shutdown  bool
	Timestamp types.BigInt
}

// StrategyWithdrawEvent event struct
type StrategyWithdrawEvent struct {
	AccountKey  solana.PublicKey
	Amount      types.BigInt
	TotalAssets types.BigInt
}

// TotalInvestedUpdatedEvent event struct
type TotalInvestedUpdatedEvent struct {
	AccountKey            solana.PublicKey
	Vault                 solana.PublicKey
	PreviousTotalInvested types.BigInt
	TotalInvested         types.BigInt
	Timestamp             types.BigInt
}
