package events

// Code generated by generate_events.go; DO NOT EDIT.

import "github.com/gagliardetto/solana-go"

// EntryFeeUpdatedEvent event struct
type EntryFeeUpdatedEvent struct {
	AccountantKey solana.PublicKey `borsh:"accountant_key"`
	EntryFee      uint64           `borsh:"entry_fee"`
}

// PerformanceFeeUpdatedEvent event struct
type PerformanceFeeUpdatedEvent struct {
	AccountantKey  solana.PublicKey `borsh:"accountant_key"`
	PerformanceFee uint64           `borsh:"performance_fee"`
}

// RedemptionFeeUpdatedEvent event struct
type RedemptionFeeUpdatedEvent struct {
	AccountantKey solana.PublicKey `borsh:"accountant_key"`
	RedemptionFee uint64           `borsh:"redemption_fee"`
}
