apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    owner: desynclabs
    app.kubernetes.io/instance: {{ .Release.Namespace }}
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 8040
      targetPort: 8040