name: Solana Indexer CI/CD

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'master' && 'prod' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image using Makefile
        run: |
          make image

      - name: Push Docker image using Makefile
        run: |
          make push

      - name: Sync Argo CD and wait for completion
        run: |
          APP_NAME="${{ vars.ARGOCD_APP_NAME }}"
          API_URL="${{ secrets.ARGOCD_API_URL }}"
          IMAGE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo dev)-$(git rev-parse --short HEAD)
          [ "${{ github.ref_name }}" != "master" ] && IMAGE_TAG="$IMAGE_TAG-dev"

          MAX_RETRIES=3
          RETRY_DELAY=10
          RETRIES=0

          until [ $RETRIES -ge $MAX_RETRIES ]
          do
            docker run --rm \
              -e ARGOCD_AUTH_TOKEN=${{ secrets.ARGOCD_AUTH_TOKEN }} \
              argoproj/argocd:v2.6.15 \
              /bin/sh -c \
              "argocd app set $APP_NAME \
              --server $API_URL \
              --grpc-web \
              --parameter image.tag=$IMAGE_TAG && \
              argocd app wait $APP_NAME \
              --server $API_URL \
              --grpc-web \
              --operation && \
              argocd app sync $APP_NAME \
              --server $API_URL \
              --grpc-web \
              --timeout 180" && break

            RETRIES=$((RETRIES+1))
            echo "Retrying... ($RETRIES/$MAX_RETRIES)"
            sleep $RETRY_DELAY
          done

          if [ $RETRIES -eq $MAX_RETRIES ]; then
            echo "Failed to sync after $MAX_RETRIES attempts"
            exit 1
          fi